# Generated by Django 3.2.25 on 2025-04-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('name', models.CharField(max_length=255)),
                ('volume', models.PositiveIntegerField(help_text='Volume in ml')),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
